BEGIN
INSERT INTO pais ( nombre) VALUES ( 'AFGHANISTAN');
INSERT INTO pais ( nombre) VALUES ( 'ALAND ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'ALBANIA');
INSERT INTO pais ( nombre) VALUES ( 'ALEMANIA');
INSERT INTO pais ( nombre) VALUES ( 'ALGERIA');
INSERT INTO pais ( nombre) VALUES ( 'AMERICAN SAMOA');
INSERT INTO pais ( nombre) VALUES ( 'ANDORRA');
INSERT INTO pais ( nombre) VALUES ( 'ANGOLA');
INSERT INTO pais ( nombre) VALUES ( 'ANGUILLA');
INSERT INTO pais ( nombre) VALUES ( 'ANTARCTICA');
INSERT INTO pais ( nombre) VALUES ( 'ANTIGUA Y BARBUDA');
INSERT INTO pais ( nombre) VALUES ( 'ARABIA SAUDITA');
INSERT INTO pais ( nombre) VALUES ( 'ARGENTINA');
INSERT INTO pais ( nombre) VALUES ( 'ARMENIA');
INSERT INTO pais ( nombre) VALUES ( 'ARUBA');
INSERT INTO pais ( nombre) VALUES ( 'ASIA / REGION PACIFICO');
INSERT INTO pais ( nombre) VALUES ( 'AUSTRALIA');
INSERT INTO pais ( nombre) VALUES ( 'AUSTRIA');
INSERT INTO pais ( nombre) VALUES ( 'AZERBAIJAN');
INSERT INTO pais ( nombre) VALUES ( 'BAHAMAS');
INSERT INTO pais ( nombre) VALUES ( 'BAHRAIN');
INSERT INTO pais ( nombre) VALUES ( 'BANGLADESH');
INSERT INTO pais ( nombre) VALUES ( 'BARBADOS');
INSERT INTO pais ( nombre) VALUES ( 'BELARUS');
INSERT INTO pais ( nombre) VALUES ( 'BELGICA');
INSERT INTO pais ( nombre) VALUES ( 'BELICE');
INSERT INTO pais ( nombre) VALUES ( 'BENIN');
INSERT INTO pais ( nombre) VALUES ( 'BERMUDA');
INSERT INTO pais ( nombre) VALUES ( 'BHUTAN');
INSERT INTO pais ( nombre) VALUES ( 'BOLIVIA');
INSERT INTO pais ( nombre) VALUES ( 'BONAIR');
INSERT INTO pais ( nombre) VALUES ( 'BOSNIA AND HERZEGOVINA');
INSERT INTO pais ( nombre) VALUES ( 'BOTSWANA');
INSERT INTO pais ( nombre) VALUES ( 'BRASIL');
INSERT INTO pais ( nombre) VALUES ( 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO pais ( nombre) VALUES ( 'BRUNEI DARUSSALAM');
INSERT INTO pais ( nombre) VALUES ( 'BULGARIA');
INSERT INTO pais ( nombre) VALUES ( 'BURKINA FASO');
INSERT INTO pais ( nombre) VALUES ( 'BURUNDI');
INSERT INTO pais ( nombre) VALUES ( 'CABO VERDE');
INSERT INTO pais ( nombre) VALUES ( 'CAMBOYA');
INSERT INTO pais ( nombre) VALUES ( 'CAMERUN');
INSERT INTO pais ( nombre) VALUES ( 'CANADA');
INSERT INTO pais ( nombre) VALUES ( 'CHAD');
INSERT INTO pais ( nombre) VALUES ( 'CHILE');
INSERT INTO pais ( nombre) VALUES ( 'CHINA');
INSERT INTO pais ( nombre) VALUES ( 'CHIPRE');
INSERT INTO pais ( nombre) VALUES ( 'COCOS (KEELING) ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'COLOMBIA');
INSERT INTO pais ( nombre) VALUES ( 'COMOROS');
INSERT INTO pais ( nombre) VALUES ( 'CONG');
INSERT INTO pais ( nombre) VALUES ( 'CONGO');
INSERT INTO pais ( nombre) VALUES ( 'COOK ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'COSTA RICA');
INSERT INTO pais ( nombre) VALUES ( 'COTE D''IVOIRE');
INSERT INTO pais ( nombre) VALUES ( 'CROACIA');
INSERT INTO pais ( nombre) VALUES ( 'CUBA');
INSERT INTO pais ( nombre) VALUES ( 'CURACAO');
INSERT INTO pais ( nombre) VALUES ( 'DINAMARCA');
INSERT INTO pais ( nombre) VALUES ( 'DJIBOUTI');
INSERT INTO pais ( nombre) VALUES ( 'DOMINICA');
INSERT INTO pais ( nombre) VALUES ( 'ECUADOR');
INSERT INTO pais ( nombre) VALUES ( 'EGIPTO');
INSERT INTO pais ( nombre) VALUES ( 'EL SALVADOR');
INSERT INTO pais ( nombre) VALUES ( 'EMIRATOS ARABES UNIDOS');
INSERT INTO pais ( nombre) VALUES ( 'ERITREA');
INSERT INTO pais ( nombre) VALUES ( 'ESLOVAQUIA');
INSERT INTO pais ( nombre) VALUES ( 'ESLOVENIA');
INSERT INTO pais ( nombre) VALUES ( 'ESPAÑA');
INSERT INTO pais ( nombre) VALUES ( 'ESTADOS UNIDOS');
INSERT INTO pais ( nombre) VALUES ( 'ESTONIA');
INSERT INTO pais ( nombre) VALUES ( 'ETIOPIA');
INSERT INTO pais ( nombre) VALUES ( 'FAROE ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'FIJI');
INSERT INTO pais ( nombre) VALUES ( 'FILIPINAS');
INSERT INTO pais ( nombre) VALUES ( 'FINLANDIA');
INSERT INTO pais ( nombre) VALUES ( 'FRANCIA');
INSERT INTO pais ( nombre) VALUES ( 'FRENCH POLYNESIA');
INSERT INTO pais ( nombre) VALUES ( 'GABON');
INSERT INTO pais ( nombre) VALUES ( 'GAMBIA');
INSERT INTO pais ( nombre) VALUES ( 'GANA');
INSERT INTO pais ( nombre) VALUES ( 'GEORGIA');
INSERT INTO pais ( nombre) VALUES ( 'GIBRALTAR');
INSERT INTO pais ( nombre) VALUES ( 'GRANADA');
INSERT INTO pais ( nombre) VALUES ( 'GRECIA');
INSERT INTO pais ( nombre) VALUES ( 'GROENLANDIA');
INSERT INTO pais ( nombre) VALUES ( 'GUADELOUPE');
INSERT INTO pais ( nombre) VALUES ( 'GUAM');
INSERT INTO pais ( nombre) VALUES ( 'GUATEMALA');
INSERT INTO pais ( nombre) VALUES ( 'GUERNSEY');
INSERT INTO pais ( nombre) VALUES ( 'GUINEA');
INSERT INTO pais ( nombre) VALUES ( 'GUINEA ECUATORIAL');
INSERT INTO pais ( nombre) VALUES ( 'GUINEA-BISSAU');
INSERT INTO pais ( nombre) VALUES ( 'GUYANA');
INSERT INTO pais ( nombre) VALUES ( 'GUYANA FRANCESA');
INSERT INTO pais ( nombre) VALUES ( 'HAITI');
INSERT INTO pais ( nombre) VALUES ( 'HOLANDA, PAISES BAJOS');
INSERT INTO pais ( nombre) VALUES ( 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO pais ( nombre) VALUES ( 'HONDURAS');
INSERT INTO pais ( nombre) VALUES ( 'HUNGRIA');
INSERT INTO pais ( nombre) VALUES ( 'INDIA');
INSERT INTO pais ( nombre) VALUES ( 'INDONESIA');
INSERT INTO pais ( nombre) VALUES ( 'IRA');
INSERT INTO pais ( nombre) VALUES ( 'IRAQ');
INSERT INTO pais ( nombre) VALUES ( 'IRLANDA');
INSERT INTO pais ( nombre) VALUES ( 'ISLANDIA');
INSERT INTO pais ( nombre) VALUES ( 'ISLAS (MALVINAS)');
INSERT INTO pais ( nombre) VALUES ( 'ISLAS CAIMAN');
INSERT INTO pais ( nombre) VALUES ( 'ISLAS DE PASCUA');
INSERT INTO pais ( nombre) VALUES ( 'ISLAS SALOMON');
INSERT INTO pais ( nombre) VALUES ( 'ISLE OF MAN');
INSERT INTO pais ( nombre) VALUES ( 'ISRAEL');
INSERT INTO pais ( nombre) VALUES ( 'ITALIA');
INSERT INTO pais ( nombre) VALUES ( 'JAMAICA');
INSERT INTO pais ( nombre) VALUES ( 'JAPAN');
INSERT INTO pais ( nombre) VALUES ( 'JERSEY');
INSERT INTO pais ( nombre) VALUES ( 'JORDAN');
INSERT INTO pais ( nombre) VALUES ( 'KAZAKHSTAN');
INSERT INTO pais ( nombre) VALUES ( 'KENYA');
INSERT INTO pais ( nombre) VALUES ( 'KIRIBATI');
INSERT INTO pais ( nombre) VALUES ( 'KORE');
INSERT INTO pais ( nombre) VALUES ( 'KUWAIT');
INSERT INTO pais ( nombre) VALUES ( 'KYRGYZSTAN');
INSERT INTO pais ( nombre) VALUES ( 'LAO PEOPLE''S DEMOCRATIC REPUBLIC');
INSERT INTO pais ( nombre) VALUES ( 'LATVIA');
INSERT INTO pais ( nombre) VALUES ( 'LEBANON');
INSERT INTO pais ( nombre) VALUES ( 'LESOTHO');
INSERT INTO pais ( nombre) VALUES ( 'LIBERIA');
INSERT INTO pais ( nombre) VALUES ( 'LIBYA');
INSERT INTO pais ( nombre) VALUES ( 'LIECHTENSTEIN');
INSERT INTO pais ( nombre) VALUES ( 'LITHUANIA');
INSERT INTO pais ( nombre) VALUES ( 'LUXEMBOURG');
INSERT INTO pais ( nombre) VALUES ( 'MACAU');
INSERT INTO pais ( nombre) VALUES ( 'MACEDONIA');
INSERT INTO pais ( nombre) VALUES ( 'MADAGASCAR');
INSERT INTO pais ( nombre) VALUES ( 'MALASIA');
INSERT INTO pais ( nombre) VALUES ( 'MALAWI');
INSERT INTO pais ( nombre) VALUES ( 'MALDIVES');
INSERT INTO pais ( nombre) VALUES ( 'MALI');
INSERT INTO pais ( nombre) VALUES ( 'MALTA');
INSERT INTO pais ( nombre) VALUES ( 'MARRUECOS');
INSERT INTO pais ( nombre) VALUES ( 'MARSHALL ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'MARTINIQUE');
INSERT INTO pais ( nombre) VALUES ( 'MAURITANIA');
INSERT INTO pais ( nombre) VALUES ( 'MAURITIUS');
INSERT INTO pais ( nombre) VALUES ( 'MAYOTTE');
INSERT INTO pais ( nombre) VALUES ( 'MEXICO');
INSERT INTO pais ( nombre) VALUES ( 'MICRONESI');
INSERT INTO pais ( nombre) VALUES ( 'MOLDOV');
INSERT INTO pais ( nombre) VALUES ( 'MONACO');
INSERT INTO pais ( nombre) VALUES ( 'MONGOLIA');
INSERT INTO pais ( nombre) VALUES ( 'MONTENEGRO');
INSERT INTO pais ( nombre) VALUES ( 'MONTSERRAT');
INSERT INTO pais ( nombre) VALUES ( 'MOZAMBIQUE');
INSERT INTO pais ( nombre) VALUES ( 'MYANMAR');
INSERT INTO pais ( nombre) VALUES ( 'NAMIBIA');
INSERT INTO pais ( nombre) VALUES ( 'NAURU');
INSERT INTO pais ( nombre) VALUES ( 'NEPAL');
INSERT INTO pais ( nombre) VALUES ( 'NICARAGUA');
INSERT INTO pais ( nombre) VALUES ( 'NIGER');
INSERT INTO pais ( nombre) VALUES ( 'NIGERIA');
INSERT INTO pais ( nombre) VALUES ( 'NIUE');
INSERT INTO pais ( nombre) VALUES ( 'NORFOLK ISLAND');
INSERT INTO pais ( nombre) VALUES ( 'NORTHERN MARIANA ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'NORUEGA');
INSERT INTO pais ( nombre) VALUES ( 'NUEVA CALEDONIA');
INSERT INTO pais ( nombre) VALUES ( 'NUEVA ZELANDIA');
INSERT INTO pais ( nombre) VALUES ( 'OMAN');
INSERT INTO pais ( nombre) VALUES ( 'PAKISTAN');
INSERT INTO pais ( nombre) VALUES ( 'PALAU');
INSERT INTO pais ( nombre) VALUES ( 'PALESTINA');
INSERT INTO pais ( nombre) VALUES ( 'PANAMA');
INSERT INTO pais ( nombre) VALUES ( 'PAPUA NEW GUINEA');
INSERT INTO pais ( nombre) VALUES ( 'PARAGUAY');
INSERT INTO pais ( nombre) VALUES ( 'PERU');
INSERT INTO pais ( nombre) VALUES ( 'PITCAIRN ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'POLONIA');
INSERT INTO pais ( nombre) VALUES ( 'PORTUGAL');
INSERT INTO pais ( nombre) VALUES ( 'PUERTO RICO');
INSERT INTO pais ( nombre) VALUES ( 'QATAR');
INSERT INTO pais ( nombre) VALUES ( 'REINO UNIDO');
INSERT INTO pais ( nombre) VALUES ( 'REPUBLICA CENTRAL DE AFRICA');
INSERT INTO pais ( nombre) VALUES ( 'REPUBLICA CHECA');
INSERT INTO pais ( nombre) VALUES ( 'REPUBLICA DOMINICANA');
INSERT INTO pais ( nombre) VALUES ( 'REUNION');
INSERT INTO pais ( nombre) VALUES ( 'ROMANIA');
INSERT INTO pais ( nombre) VALUES ( 'RUANDA');
INSERT INTO pais ( nombre) VALUES ( 'RUSIA');
INSERT INTO pais ( nombre) VALUES ( 'SAINT BARTHELEMY');
INSERT INTO pais ( nombre) VALUES ( 'SAINT HELENA');
INSERT INTO pais ( nombre) VALUES ( 'SAINT KITTS AND NEVIS');
INSERT INTO pais ( nombre) VALUES ( 'SAINT PIERRE AND MIQUELON');
INSERT INTO pais ( nombre) VALUES ( 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO pais ( nombre) VALUES ( 'SAMOA');
INSERT INTO pais ( nombre) VALUES ( 'SAN MARINO');
INSERT INTO pais ( nombre) VALUES ( 'SAN MARTIN');
INSERT INTO pais ( nombre) VALUES ( 'SANTA LUCIA');
INSERT INTO pais ( nombre) VALUES ( 'SAO TOME AND PRINCIPE');
INSERT INTO pais ( nombre) VALUES ( 'SENEGAL');
INSERT INTO pais ( nombre) VALUES ( 'SERBIA');
INSERT INTO pais ( nombre) VALUES ( 'SEYCHELLES');
INSERT INTO pais ( nombre) VALUES ( 'SIERRA LEONE');
INSERT INTO pais ( nombre) VALUES ( 'SINGAPUR');
INSERT INTO pais ( nombre) VALUES ( 'SINT MAARTEN (DUTCH PART)');
INSERT INTO pais ( nombre) VALUES ( 'SIRIA REPUBLICA ARABE');
INSERT INTO pais ( nombre) VALUES ( 'SOMALIA');
INSERT INTO pais ( nombre) VALUES ( 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'SRI LANKA');
INSERT INTO pais ( nombre) VALUES ( 'SUDAFRICA');
INSERT INTO pais ( nombre) VALUES ( 'SUDAN');
INSERT INTO pais ( nombre) VALUES ( 'SUDAN DEL SUR');
INSERT INTO pais ( nombre) VALUES ( 'SUECIA');
INSERT INTO pais ( nombre) VALUES ( 'SUIZA');
INSERT INTO pais ( nombre) VALUES ( 'SURINAM');
INSERT INTO pais ( nombre) VALUES ( 'SVALBARD AND JAN MAYEN');
INSERT INTO pais ( nombre) VALUES ( 'SWAZILAND');
INSERT INTO pais ( nombre) VALUES ( 'TAILANDIA');
INSERT INTO pais ( nombre) VALUES ( 'TAIWAN');
INSERT INTO pais ( nombre) VALUES ( 'TAJIKISTAN');
INSERT INTO pais ( nombre) VALUES ( 'TANZANIA');
INSERT INTO pais ( nombre) VALUES ( 'TIMOR-LESTE');
INSERT INTO pais ( nombre) VALUES ( 'TOGO');
INSERT INTO pais ( nombre) VALUES ( 'TOKELAU');
INSERT INTO pais ( nombre) VALUES ( 'TONGA');
INSERT INTO pais ( nombre) VALUES ( 'TRINIDAD Y TOBAGO');
INSERT INTO pais ( nombre) VALUES ( 'TUNISIA');
INSERT INTO pais ( nombre) VALUES ( 'TURKMENISTAN');
INSERT INTO pais ( nombre) VALUES ( 'TURKS AND CAICOS ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'TURQUIA');
INSERT INTO pais ( nombre) VALUES ( 'TUVALU');
INSERT INTO pais ( nombre) VALUES ( 'UCRANIA');
INSERT INTO pais ( nombre) VALUES ( 'UGANDA');
INSERT INTO pais ( nombre) VALUES ( 'UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'URUGUAY');
INSERT INTO pais ( nombre) VALUES ( 'UZBEKISTAN');
INSERT INTO pais ( nombre) VALUES ( 'VANUATU');
INSERT INTO pais ( nombre) VALUES ( 'VENEZUELA');
INSERT INTO pais ( nombre) VALUES ( 'VIETNAM');
INSERT INTO pais ( nombre) VALUES ( 'VIRGIN ISLAND');
INSERT INTO pais ( nombre) VALUES ( 'WALLIS AND FUTUNA');
INSERT INTO pais ( nombre) VALUES ( 'WESTERN SAHARA');
INSERT INTO pais ( nombre) VALUES ( 'YEMEN');
INSERT INTO pais ( nombre) VALUES ( 'ZAMBIA');
INSERT INTO pais ( nombre) VALUES ( 'ZIMBABWE');
INSERT INTO pais ( nombre) VALUES ( 'SABA');
INSERT INTO pais ( nombre) VALUES ( 'SAINT EUSTATIUS');
INSERT INTO pais ( nombre) VALUES ( 'ISLA SANTA CRUZ');
INSERT INTO pais ( nombre) VALUES ( 'ISLA SANTO TOMAS');
INSERT INTO pais ( nombre) VALUES ( 'ISLA SAN JUAN');

COMMIT;
END