// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(SupplierAPIDbContext))]
    [Migration("20231221043823_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Models.CatalogoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<int?>("Requerido")
                        .HasColumnType("int")
                        .HasColumnName("requerido");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoDocumentoId");

                    b.HasKey("Id")
                        .HasName("PK_CatalogoDocumentoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("CatalogoDocumento", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprador")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("comprador");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("estadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("GrupoCompra")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("grupoCompra");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_CategoriaId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int?>("PaisId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("PaisId");

                    b.HasKey("Id")
                        .HasName("PK_CiudadId");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudad", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.ConfiguracionGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Valor1")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Valor1");

                    b.Property<string>("Valor2")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Valor2");

                    b.Property<string>("Valor3")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Valor3");

                    b.Property<string>("Valor4")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Valor4");

                    b.Property<string>("Valor5")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Valor5");

                    b.HasKey("Id")
                        .HasName("PK_ConfiguracionGeneralId");

                    b.HasIndex("EstadoId");

                    b.ToTable("ConfiguracionGeneral", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.ConfiguracionNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<int?>("Dias")
                        .HasColumnType("int")
                        .HasColumnName("dias");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<TimeSpan?>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.HasKey("Id")
                        .HasName("PK_ConfiguracionNotificacionId");

                    b.HasIndex("EstadoId");

                    b.ToTable("ConfiguracionNotificacion", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CatalogoDocumentoId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("CatalogoDocumentoId");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<int?>("EstadoId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaEmicion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaEmicion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaVencimiento");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Nombre");

                    b.Property<int?>("ProveedorId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("ProveedorId");

                    b.HasKey("Id")
                        .HasName("PK_CocumentoId");

                    b.HasIndex("CatalogoDocumentoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_EstadoId");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_PaisId");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Aspirante")
                        .HasColumnType("int")
                        .HasColumnName("Aspitante");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int")
                        .HasColumnName("CiudadId");

                    b.Property<string>("CodigoProveedorSap")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CodigoProveedorSap");

                    b.Property<string>("ContactoPrimario")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ContactoPrimario");

                    b.Property<string>("ContactoSecundario")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ContactoSecundario");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Empresa")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Empresa");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Identificacion");

                    b.Property<string>("IdentificacionTipo")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("IdentificacionTipo");

                    b.Property<string>("Idioma")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Idioma");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Movil")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Movil");

                    b.Property<string>("Observacion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Observacion");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PaginaWeb");

                    b.Property<int>("SubtipoCompraId")
                        .HasColumnType("int")
                        .HasColumnName("SubtipoCompraId");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Telefono");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id")
                        .HasName("PK_ProveedorId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("SubtipoCompraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.ProveedorCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ProveedorCategoria");
                });

            modelBuilder.Entity("DomainLayer.Models.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Contacto");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<int?>("EstadoId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<int?>("ProveedorId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("ProveedorId");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id")
                        .HasName("PK_ReferenciaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Referencia", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_RolId");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id")
                        .HasName("PK_RolUsuarioId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RolUsuario", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.SubtipoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("TipoCompraId")
                        .HasColumnType("int")
                        .HasColumnName("TipoCompraId");

                    b.HasKey("Id")
                        .HasName("PK_SubtipoCompraId");

                    b.HasIndex("TipoCompraId");

                    b.ToTable("SubtipoCompra", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.TipoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<string>("TipoCompras")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("TipoCompra");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<int?>("EstadoId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_TipoDocumentoId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Tipo_Documento", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoId");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("UserIdAzure")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("UserIdAzure");

                    b.HasKey("Id")
                        .HasName("PK_UsiarioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.CatalogoDocumento", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("CatalogoDocumentos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CatalogoDocumento_Estado");

                    b.HasOne("DomainLayer.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("CatalogoDocumentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CatalogoDocumento_TipoDocumento");

                    b.Navigation("Estado");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("DomainLayer.Models.Categoria", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("Categorias")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Categoria_Estado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DomainLayer.Models.Ciudad", b =>
                {
                    b.HasOne("DomainLayer.Models.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ciudad_Pais");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DomainLayer.Models.ConfiguracionGeneral", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estados")
                        .WithMany("ConfiguracionGeneral")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConfiguracionGeneral_Estado");

                    b.Navigation("Estados");
                });

            modelBuilder.Entity("DomainLayer.Models.ConfiguracionNotificacion", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("ConfiguracionNotificaciones")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConfiguracionNotificacion_Estado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DomainLayer.Models.Documento", b =>
                {
                    b.HasOne("DomainLayer.Models.CatalogoDocumento", "CatalogoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("CatalogoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Documento_CatalogoDocumento");

                    b.HasOne("DomainLayer.Models.Estado", "Estados")
                        .WithMany("Documentos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Documento_Estado");

                    b.HasOne("DomainLayer.Models.Proveedor", "Proveedor")
                        .WithMany("Documentos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Documento_Proveedor");

                    b.Navigation("CatalogoDocumento");

                    b.Navigation("Estados");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("DomainLayer.Models.Proveedor", b =>
                {
                    b.HasOne("DomainLayer.Models.Ciudad", "Ciudad")
                        .WithMany("Proveedores")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_Ciudad");

                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("Proveedores")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_Estado");

                    b.HasOne("DomainLayer.Models.SubtipoCompra", "SubtipoCompra")
                        .WithMany("Proveedores")
                        .HasForeignKey("SubtipoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_SubtipoCompra");

                    b.HasOne("DomainLayer.Models.Usuario", "Usuario")
                        .WithMany("Proveedores")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_Usuario");

                    b.Navigation("Ciudad");

                    b.Navigation("Estado");

                    b.Navigation("SubtipoCompra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DomainLayer.Models.ProveedorCategoria", b =>
                {
                    b.HasOne("DomainLayer.Models.Categoria", "Categoria")
                        .WithMany("ProveedorCategorias")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("DomainLayer.Models.Proveedor", "Proveedor")
                        .WithMany("ProveedorCategorias")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("DomainLayer.Models.Referencia", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("Referencias")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Referencia_Estado");

                    b.HasOne("DomainLayer.Models.Proveedor", "Proveedor")
                        .WithMany("Referencias")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Referencia_Proveedor");

                    b.Navigation("Estado");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("DomainLayer.Models.RolUsuario", b =>
                {
                    b.HasOne("DomainLayer.Models.Rol", "Rol")
                        .WithMany("RolUsuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUsuario_Rol");

                    b.HasOne("DomainLayer.Models.Usuario", "Usuario")
                        .WithMany("RolUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUsuario_Usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DomainLayer.Models.SubtipoCompra", b =>
                {
                    b.HasOne("DomainLayer.Models.TipoCompra", "TipoCompra")
                        .WithMany("SubtipoCompras")
                        .HasForeignKey("TipoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SubtipoCompra_TipoCompra");

                    b.Navigation("TipoCompra");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoCompra", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("TipoCompras")
                        .HasForeignKey("EstadoId");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoDocumento", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("TipoDocumentos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TipoDocumento_Estado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DomainLayer.Models.Usuario", b =>
                {
                    b.HasOne("DomainLayer.Models.Estado", "Estado")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Estado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("DomainLayer.Models.CatalogoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("DomainLayer.Models.Categoria", b =>
                {
                    b.Navigation("ProveedorCategorias");
                });

            modelBuilder.Entity("DomainLayer.Models.Ciudad", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("DomainLayer.Models.Estado", b =>
                {
                    b.Navigation("CatalogoDocumentos");

                    b.Navigation("Categorias");

                    b.Navigation("ConfiguracionGeneral");

                    b.Navigation("ConfiguracionNotificaciones");

                    b.Navigation("Documentos");

                    b.Navigation("Proveedores");

                    b.Navigation("Referencias");

                    b.Navigation("TipoCompras");

                    b.Navigation("TipoDocumentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DomainLayer.Models.Pais", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("DomainLayer.Models.Proveedor", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("ProveedorCategorias");

                    b.Navigation("Referencias");
                });

            modelBuilder.Entity("DomainLayer.Models.Rol", b =>
                {
                    b.Navigation("RolUsuarios");
                });

            modelBuilder.Entity("DomainLayer.Models.SubtipoCompra", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoCompra", b =>
                {
                    b.Navigation("SubtipoCompras");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoDocumento", b =>
                {
                    b.Navigation("CatalogoDocumentos");
                });

            modelBuilder.Entity("DomainLayer.Models.Usuario", b =>
                {
                    b.Navigation("Proveedores");

                    b.Navigation("RolUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
