BEGIN
INSERT INTO pais ( nombre) VALUES ( 'INDIA');
INSERT INTO pais ( nombre) VALUES ( 'PAKISTAN');
INSERT INTO pais ( nombre) VALUES ( 'AFGHANISTAN');
INSERT INTO pais ( nombre) VALUES ( 'ALBANIA');
INSERT INTO pais ( nombre) VALUES ( 'ALGERIA');
INSERT INTO pais ( nombre) VALUES ( 'AMERICAN SAMOA');
INSERT INTO pais ( nombre) VALUES ( 'ANDORRA');
INSERT INTO pais ( nombre) VALUES ( 'ANGOLA');
INSERT INTO pais ( nombre) VALUES ( 'ANTIGUA AND BARBUDA');
INSERT INTO pais ( nombre) VALUES ( 'ARGENTINA');
INSERT INTO pais ( nombre) VALUES ( 'ARMENIA');
INSERT INTO pais ( nombre) VALUES ( 'ARUBA');
INSERT INTO pais ( nombre) VALUES ( 'AUSTRALIA');
INSERT INTO pais ( nombre) VALUES ( 'AUSTRIA');
INSERT INTO pais ( nombre) VALUES ( 'AZERBAIJAN');
INSERT INTO pais ( nombre) VALUES ( 'BAHAMAS THE');
INSERT INTO pais ( nombre) VALUES ( 'BAHRAIN');
INSERT INTO pais ( nombre) VALUES ( 'BANGLADESH');
INSERT INTO pais ( nombre) VALUES ( 'BELARUS');
INSERT INTO pais ( nombre) VALUES ( 'BELGIUM');
INSERT INTO pais ( nombre) VALUES ( 'BELIZE');
INSERT INTO pais ( nombre) VALUES ( 'BENIN');
INSERT INTO pais ( nombre) VALUES ( 'BERMUDA');
INSERT INTO pais ( nombre) VALUES ( 'BHUTAN');
INSERT INTO pais ( nombre) VALUES ( 'BOLIVIA');
INSERT INTO pais ( nombre) VALUES ( 'BOTSWANA');
INSERT INTO pais ( nombre) VALUES ( 'BRAZIL');
INSERT INTO pais ( nombre) VALUES ( 'BRUNEI');
INSERT INTO pais ( nombre) VALUES ( 'BULGARIA');
INSERT INTO pais ( nombre) VALUES ( 'BURKINA FASO');
INSERT INTO pais ( nombre) VALUES ( 'BURUNDI');
INSERT INTO pais ( nombre) VALUES ( 'CAMBODIA');
INSERT INTO pais ( nombre) VALUES ( 'CAMEROON');
INSERT INTO pais ( nombre) VALUES ( 'CANADA');
INSERT INTO pais ( nombre) VALUES ( 'CAPE VERDE');
INSERT INTO pais ( nombre) VALUES ( 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO pais ( nombre) VALUES ( 'CHAD');
INSERT INTO pais ( nombre) VALUES ( 'CHILE');
INSERT INTO pais ( nombre) VALUES ( 'CHINA');
INSERT INTO pais ( nombre) VALUES ( 'COLOMBIA');
INSERT INTO pais ( nombre) VALUES ( 'COMOROS');
INSERT INTO pais ( nombre) VALUES ( 'REPUBLIC OF THE CONGO');
INSERT INTO pais ( nombre) VALUES ( 'DEMOCRATIC REPUBLIC OF THE CONGO');
INSERT INTO pais ( nombre) VALUES ( 'COOK ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'COSTA RICA');
INSERT INTO pais ( nombre) VALUES ( 'COTE DIVOIRE (IVORY COAST)');
INSERT INTO pais ( nombre) VALUES ( 'CROATIA (HRVATSKA)');
INSERT INTO pais ( nombre) VALUES ( 'CUBA');
INSERT INTO pais ( nombre) VALUES ( 'CYPRUS');
INSERT INTO pais ( nombre) VALUES ( 'CZECH REPUBLIC');
INSERT INTO pais ( nombre) VALUES ( 'DENMARK');
INSERT INTO pais ( nombre) VALUES ( 'DJIBOUTI');
INSERT INTO pais ( nombre) VALUES ( 'DOMINICAN REPUBLIC');
INSERT INTO pais ( nombre) VALUES ( 'EAST TIMOR');
INSERT INTO pais ( nombre) VALUES ( 'ECUADOR');
INSERT INTO pais ( nombre) VALUES ( 'EGYPT');
INSERT INTO pais ( nombre) VALUES ( 'EL SALVADOR');
INSERT INTO pais ( nombre) VALUES ( 'EQUATORIAL GUINEA');
INSERT INTO pais ( nombre) VALUES ( 'ERITREA');
INSERT INTO pais ( nombre) VALUES ( 'ESTONIA');
INSERT INTO pais ( nombre) VALUES ( 'ETHIOPIA');
INSERT INTO pais ( nombre) VALUES ( 'FAROE ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'FIJI ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'FINLAND');
INSERT INTO pais ( nombre) VALUES ( 'FRANCE');
INSERT INTO pais ( nombre) VALUES ( 'FRENCH GUIANA');
INSERT INTO pais ( nombre) VALUES ( 'FRENCH POLYNESIA');
INSERT INTO pais ( nombre) VALUES ( 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO pais ( nombre) VALUES ( 'GABON');
INSERT INTO pais ( nombre) VALUES ( 'GAMBIA THE');
INSERT INTO pais ( nombre) VALUES ( 'GEORGIA');
INSERT INTO pais ( nombre) VALUES ( 'GERMANY');
INSERT INTO pais ( nombre) VALUES ( 'GHANA');
INSERT INTO pais ( nombre) VALUES ( 'GIBRALTAR');
INSERT INTO pais ( nombre) VALUES ( 'GREECE');
INSERT INTO pais ( nombre) VALUES ( 'GREENLAND');
INSERT INTO pais ( nombre) VALUES ( 'GUADELOUPE');
INSERT INTO pais ( nombre) VALUES ( 'GUAM');
INSERT INTO pais ( nombre) VALUES ( 'GUATEMALA');
INSERT INTO pais ( nombre) VALUES ( 'GUERNSEY AND ALDERNEY');
INSERT INTO pais ( nombre) VALUES ( 'GUINEA');
INSERT INTO pais ( nombre) VALUES ( 'GUINEA-BISSAU');
INSERT INTO pais ( nombre) VALUES ( 'GUYANA');
INSERT INTO pais ( nombre) VALUES ( 'HAITI');
INSERT INTO pais ( nombre) VALUES ( 'HONDURAS');
INSERT INTO pais ( nombre) VALUES ( 'HUNGARY');
INSERT INTO pais ( nombre) VALUES ( 'ICELAND');
INSERT INTO pais ( nombre) VALUES ( 'INDONESIA');
INSERT INTO pais ( nombre) VALUES ( 'IRAN');
INSERT INTO pais ( nombre) VALUES ( 'IRAQ');
INSERT INTO pais ( nombre) VALUES ( 'IRELAND');
INSERT INTO pais ( nombre) VALUES ( 'ISRAEL');
INSERT INTO pais ( nombre) VALUES ( 'ITALY');
INSERT INTO pais ( nombre) VALUES ( 'JAMAICA');
INSERT INTO pais ( nombre) VALUES ( 'JAPAN');
INSERT INTO pais ( nombre) VALUES ( 'JERSEY');
INSERT INTO pais ( nombre) VALUES ( 'JORDAN');
INSERT INTO pais ( nombre) VALUES ( 'KAZAKHSTAN');
INSERT INTO pais ( nombre) VALUES ( 'KENYA');
INSERT INTO pais ( nombre) VALUES ( 'KIRIBATI');
INSERT INTO pais ( nombre) VALUES ( 'KOREA NORTH');
INSERT INTO pais ( nombre) VALUES ( 'KOREA SOUTH');
INSERT INTO pais ( nombre) VALUES ( 'KUWAIT');
INSERT INTO pais ( nombre) VALUES ( 'KYRGYZSTAN');
INSERT INTO pais ( nombre) VALUES ( 'LAOS');
INSERT INTO pais ( nombre) VALUES ( 'LATVIA');
INSERT INTO pais ( nombre) VALUES ( 'LEBANON');
INSERT INTO pais ( nombre) VALUES ( 'LESOTHO');
INSERT INTO pais ( nombre) VALUES ( 'LIBERIA');
INSERT INTO pais ( nombre) VALUES ( 'LIBYA');
INSERT INTO pais ( nombre) VALUES ( 'LIECHTENSTEIN');
INSERT INTO pais ( nombre) VALUES ( 'LITHUANIA');
INSERT INTO pais ( nombre) VALUES ( 'LUXEMBOURG');
INSERT INTO pais ( nombre) VALUES ( 'MACAU S.A.R.');
INSERT INTO pais ( nombre) VALUES ( 'MACEDONIA');
INSERT INTO pais ( nombre) VALUES ( 'MADAGASCAR');
INSERT INTO pais ( nombre) VALUES ( 'MALAWI');
INSERT INTO pais ( nombre) VALUES ( 'MALAYSIA');
INSERT INTO pais ( nombre) VALUES ( 'MALDIVES');
INSERT INTO pais ( nombre) VALUES ( 'MALI');
INSERT INTO pais ( nombre) VALUES ( 'MALTA');
INSERT INTO pais ( nombre) VALUES ( 'MAN (ISLE OF)');
INSERT INTO pais ( nombre) VALUES ( 'MARSHALL ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'MARTINIQUE');
INSERT INTO pais ( nombre) VALUES ( 'MAURITANIA');
INSERT INTO pais ( nombre) VALUES ( 'MAURITIUS');
INSERT INTO pais ( nombre) VALUES ( 'MAYOTTE');
INSERT INTO pais ( nombre) VALUES ( 'MEXICO');
INSERT INTO pais ( nombre) VALUES ( 'MICRONESIA');
INSERT INTO pais ( nombre) VALUES ( 'MOLDOVA');
INSERT INTO pais ( nombre) VALUES ( 'MONACO');
INSERT INTO pais ( nombre) VALUES ( 'MONGOLIA');
INSERT INTO pais ( nombre) VALUES ( 'MONTSERRAT');
INSERT INTO pais ( nombre) VALUES ( 'MOROCCO');
INSERT INTO pais ( nombre) VALUES ( 'MOZAMBIQUE');
INSERT INTO pais ( nombre) VALUES ( 'MYANMAR');
INSERT INTO pais ( nombre) VALUES ( 'NAMIBIA');
INSERT INTO pais ( nombre) VALUES ( 'NAURU');
INSERT INTO pais ( nombre) VALUES ( 'NEPAL');
INSERT INTO pais ( nombre) VALUES ( 'NETHERLANDS ANTILLES');
INSERT INTO pais ( nombre) VALUES ( 'NETHERLANDS THE');
INSERT INTO pais ( nombre) VALUES ( 'NEW CALEDONIA');
INSERT INTO pais ( nombre) VALUES ( 'NEW ZEALAND');
INSERT INTO pais ( nombre) VALUES ( 'NICARAGUA');
INSERT INTO pais ( nombre) VALUES ( 'NIGER');
INSERT INTO pais ( nombre) VALUES ( 'NIGERIA');
INSERT INTO pais ( nombre) VALUES ( 'NIUE');
INSERT INTO pais ( nombre) VALUES ( 'NORTHERN MARIANA ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'NORWAY');
INSERT INTO pais ( nombre) VALUES ( 'OMAN');
INSERT INTO pais ( nombre) VALUES ( 'PALAU');
INSERT INTO pais ( nombre) VALUES ( 'PALESTINIAN TERRITORY OCCUPIED');
INSERT INTO pais ( nombre) VALUES ( 'PANAMA');
INSERT INTO pais ( nombre) VALUES ( 'PAPUA NEW GUINEA');
INSERT INTO pais ( nombre) VALUES ( 'PARAGUAY');
INSERT INTO pais ( nombre) VALUES ( 'PERU');
INSERT INTO pais ( nombre) VALUES ( 'PHILIPPINES');
INSERT INTO pais ( nombre) VALUES ( 'POLAND');
INSERT INTO pais ( nombre) VALUES ( 'PORTUGAL');
INSERT INTO pais ( nombre) VALUES ( 'PUERTO RICO');
INSERT INTO pais ( nombre) VALUES ( 'QATAR');
INSERT INTO pais ( nombre) VALUES ( 'REUNION');
INSERT INTO pais ( nombre) VALUES ( 'ROMANIA');
INSERT INTO pais ( nombre) VALUES ( 'RUSSIA');
INSERT INTO pais ( nombre) VALUES ( 'RWANDA');
INSERT INTO pais ( nombre) VALUES ( 'SAINT HELENA');
INSERT INTO pais ( nombre) VALUES ( 'SAINT LUCIA');
INSERT INTO pais ( nombre) VALUES ( 'SAINT PIERRE AND MIQUELON');
INSERT INTO pais ( nombre) VALUES ( 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO pais ( nombre) VALUES ( 'SAMOA');
INSERT INTO pais ( nombre) VALUES ( 'SAN MARINO');
INSERT INTO pais ( nombre) VALUES ( 'SAO TOME AND PRINCIPE');
INSERT INTO pais ( nombre) VALUES ( 'SAUDI ARABIA');
INSERT INTO pais ( nombre) VALUES ( 'SENEGAL');
INSERT INTO pais ( nombre) VALUES ( 'SEYCHELLES');
INSERT INTO pais ( nombre) VALUES ( 'SIERRA LEONE');
INSERT INTO pais ( nombre) VALUES ( 'SINGAPORE');
INSERT INTO pais ( nombre) VALUES ( 'SLOVAKIA');
INSERT INTO pais ( nombre) VALUES ( 'SLOVENIA');
INSERT INTO pais ( nombre) VALUES ( 'SMALLER TERRITORIES OF THE UK');
INSERT INTO pais ( nombre) VALUES ( 'SOLOMON ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'SOMALIA');
INSERT INTO pais ( nombre) VALUES ( 'SOUTH AFRICA');
INSERT INTO pais ( nombre) VALUES ( 'SPAIN');
INSERT INTO pais ( nombre) VALUES ( 'SRI LANKA');
INSERT INTO pais ( nombre) VALUES ( 'SUDAN');
INSERT INTO pais ( nombre) VALUES ( 'SURINAME');
INSERT INTO pais ( nombre) VALUES ( 'SVALBARD AND JAN MAYEN ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'SWAZILAND');
INSERT INTO pais ( nombre) VALUES ( 'SWEDEN');
INSERT INTO pais ( nombre) VALUES ( 'SWITZERLAND');
INSERT INTO pais ( nombre) VALUES ( 'SYRIA');
INSERT INTO pais ( nombre) VALUES ( 'TAIWAN');
INSERT INTO pais ( nombre) VALUES ( 'TAJIKISTAN');
INSERT INTO pais ( nombre) VALUES ( 'TANZANIA');
INSERT INTO pais ( nombre) VALUES ( 'THAILAND');
INSERT INTO pais ( nombre) VALUES ( 'TOGO');
INSERT INTO pais ( nombre) VALUES ( 'TOKELAU');
INSERT INTO pais ( nombre) VALUES ( 'TONGA');
INSERT INTO pais ( nombre) VALUES ( 'TRINIDAD AND TOBAGO');
INSERT INTO pais ( nombre) VALUES ( 'TUNISIA');
INSERT INTO pais ( nombre) VALUES ( 'TURKEY');
INSERT INTO pais ( nombre) VALUES ( 'TURKMENISTAN');
INSERT INTO pais ( nombre) VALUES ( 'TUVALU');
INSERT INTO pais ( nombre) VALUES ( 'UGANDA');
INSERT INTO pais ( nombre) VALUES ( 'UKRAINE');
INSERT INTO pais ( nombre) VALUES ( 'UNITED ARAB EMIRATES');
INSERT INTO pais ( nombre) VALUES ( 'UNITED KINGDOM');
INSERT INTO pais ( nombre) VALUES ( 'UNITED STATES');
INSERT INTO pais ( nombre) VALUES ( 'URUGUAY');
INSERT INTO pais ( nombre) VALUES ( 'UZBEKISTAN');
INSERT INTO pais ( nombre) VALUES ( 'VANUATU');
INSERT INTO pais ( nombre) VALUES ( 'VENEZUELA');
INSERT INTO pais ( nombre) VALUES ( 'VIETNAM');
INSERT INTO pais ( nombre) VALUES ( 'VIRGIN ISLANDS (BRITISH)');
INSERT INTO pais ( nombre) VALUES ( 'WALLIS AND FUTUNA ISLANDS');
INSERT INTO pais ( nombre) VALUES ( 'WESTERN SAHARA');
INSERT INTO pais ( nombre) VALUES ( 'YEMEN');
INSERT INTO pais ( nombre) VALUES ( 'YUGOSLAVIA');
INSERT INTO pais ( nombre) VALUES ( 'ZAMBIA');
INSERT INTO pais ( nombre) VALUES ( 'ZIMBABWE');

COMMIT;
END
